name: CI

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    branches:
      - 'master'
      - 'binary'
    paths-ignore:
      - "**.md"

jobs:
  test:
    needs: [lint]
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Test plugin
        uses: asdf-vm/actions/plugin-test@v3
        with:
          command: ruby -v
  test-binary-linux:
    needs: [lint]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Test plugin (travis)
        uses: asdf-vm/actions/plugin-test@v3
        env:
          RUBY_BINARY_INSTALL: travis
        with:
          command: ruby -v
          version: 3.3.5
      - name: Test plugin (rvm)
        uses: asdf-vm/actions/plugin-test@v3
        env:
          RUBY_BINARY_INSTALL: rvm
        with:
          command: ruby -v
          version: 3.2.3
      - name: Test plugin (custom)
        uses: asdf-vm/actions/plugin-test@v3
        env:
          RUBY_BINARY_INSTALL: https://github.com/malept/ruby-builder/releases/download/binaries/ruby-{ruby_version}_{os}-{arch}_{distro}-{distro_version}.tar.xz
        with:
          command: ruby -v
          version: 3.1.6
  test-binary-macos:
    needs: [lint]
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test plugin (custom)
        uses: asdf-vm/actions/plugin-test@v3
        env:
          RUBY_BINARY_INSTALL: https://github.com/malept/ruby-builder/releases/download/binaries/ruby-{ruby_version}_{os}-{arch}_{distro}-{distro_version}.tar.xz
          RUBY_BINARY_INSTALL_GITHUB_ATTESTATION: malept/ruby-builder
        with:
          command: ruby -v
          version: 3.2.6

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        run: shellcheck bin/* lib/*

  format:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install shfmt
        run: brew install shfmt

      - name: Run shfmt
        run: shfmt -i 2 -d bin/ lib/
