name: CI

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    branches:
      - 'master'
      - 'binary'
    paths-ignore:
      - "**.md"

jobs:
  test:
    needs: [lint]
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Test plugin
        uses: asdf-vm/actions/plugin-test@v3
        with:
          command: ruby -v
  test-binary:
    needs: [lint]
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Test plugin (travis)
        uses: asdf-vm/actions/plugin-test@v3
        env:
          RUBY_INSTALL_BINARY: travis
        with:
          command: ruby -v
          version: 3.3.5
      - name: Test plugin (rvm)
        uses: asdf-vm/actions/plugin-test@v3
        env:
          RUBY_INSTALL_BINARY: rvm
        with:
          command: ruby -v
          version: 3.2.3

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        run: shellcheck bin/* lib/*

  format:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install shfmt
        run: brew install shfmt

      - name: Run shfmt
        run: shfmt -i 2 -d bin/ lib/
