name: CI

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    branches:
      - 'master'
      - 'binary'
    paths-ignore:
      - "**.md"

jobs:
  test:
    needs: [lint]
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Test plugin
        uses: asdf-vm/actions/plugin-test@v3
        with:
          command: ruby -v
  test-precompiled-linux:
    needs: [lint]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Test plugin
        uses: asdf-vm/actions/plugin-test@v3
        env:
          GH_TOKEN: ${{ github.token }}
          ASDF_RUBY_PRECOMPILED_URL: https://github.com/malept/ruby-builder/releases/download/binaries/ruby-{ruby_version}_{os}-{arch}_{distro}-{distro_version}.tar.xz
          ASDF_RUBY_PRECOMPILED_GITHUB_ATTESTATION: malept/ruby-builder
        with:
          command: ruby -v
          version: 3.1.6
      - name: Test plugin (Homebrew/portable-ruby)
        uses: asdf-vm/actions/plugin-test@v3
        env:
          GH_TOKEN: ${{ github.token }}
          ASDF_RUBY_PRECOMPILED_URL: https://github.com/Homebrew/homebrew-portable-ruby/releases/download/{version}/portable-ruby-{version}.{arch}_{os}.bottle.tar.gz
          ASDF_RUBY_PRECOMPILED_TAR_ARGS: --strip-components=2
        with:
          command: ruby -v
          version: 3.3.7
  test-precompiled-macos:
    needs: [lint]
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test plugin
        uses: asdf-vm/actions/plugin-test@v3
        env:
          GH_TOKEN: ${{ github.token }}
          ASDF_RUBY_PRECOMPILED_URL: https://github.com/malept/ruby-builder/releases/download/binaries/ruby-{ruby_version}_{os}-{arch}_{distro}-{distro_version}.tar.xz
          ASDF_RUBY_PRECOMPILED_GITHUB_ATTESTATION: malept/ruby-builder
        with:
          command: ruby -v
          version: 3.2.6
      - name: Test plugin (Homebrew/portable-ruby)
        uses: asdf-vm/actions/plugin-test@v3
        env:
          GH_TOKEN: ${{ github.token }}
          ASDF_RUBY_PRECOMPILED_URL: https://github.com/Homebrew/homebrew-portable-ruby/releases/download/{version}/portable-ruby-{version}.arm64_bigsur.bottle.tar.gz
          ASDF_RUBY_PRECOMPILED_TAR_ARGS: --strip-components=2
        with:
          command: ruby -v
          version: 3.2.6

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        run: shellcheck bin/* lib/*

  format:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install shfmt
        run: brew install shfmt

      - name: Run shfmt
        run: shfmt -i 2 -d bin/ lib/
